package com.qpyy.libcommon.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qpyy.libcommon.db.table.MusicTable;

import com.qpyy.libcommon.db.MusicTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicTableDaoConfig;

    private final MusicTableDao musicTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicTableDaoConfig = daoConfigMap.get(MusicTableDao.class).clone();
        musicTableDaoConfig.initIdentityScope(type);

        musicTableDao = new MusicTableDao(musicTableDaoConfig, this);

        registerDao(MusicTable.class, musicTableDao);
    }
    
    public void clear() {
        musicTableDaoConfig.clearIdentityScope();
    }

    public MusicTableDao getMusicTableDao() {
        return musicTableDao;
    }

}
